version: 2
updates:
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
    time: "14:00"
    timezone: "Etc/UCT"
  versioning-strategy: increase
  commit-message:
      prefix: "chore:"
