version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Etc/UCT
  ignore:
  - dependency-name: coveralls
    versions:
    - "> 2.11.16, < 3"
  - dependency-name: coveralls
    versions:
    - ">= 3.a, < 4"
  - dependency-name: husky
    versions:
    - ">= 5.a, < 6"
  - dependency-name: sinon
    versions:
    - 10.0.0
  - dependency-name: eslint
    versions:
    - 7.20.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
