packages:
  - 'packages/*'
  - 'projects/*/packages/*'
  - 'projects/vscode-mta-tools'
  - 'examples/*'
allowBuilds:
  '@vscode/vsce-sign': true
  bufferutil: true
  core-js: true
  ejs: true
  es5-ext: true
  esbuild: true
  keytar: true
  utf-8-validate: true
