packages:
  - 'packages/*'
  - 'projects/*/packages/*'
  - 'projects/*'
  - 'examples/*'
overrides:
  'yeoman-environment@6>mem-fs': '4.1.4'
  'yeoman-environment@6>mem-fs-editor': '12.0.4'
allowBuilds:
  '@vscode/vsce-sign': true
  bufferutil: true
  core-js: true
  ejs: true
  es5-ext: true
  esbuild: true
  keytar: true
  utf-8-validate: true
