packages:
  - 'packages/*'
  - 'projects/yeoman-ui/packages/*'
  - 'examples/*'
allowBuilds:
  '@vscode/vsce-sign': true
  bufferutil: true
  core-js: true
  ejs: true
  es5-ext: true
  esbuild: true
  keytar: true
  utf-8-validate: true
overrides:
  '@types/lodash': '4.14.202'
  terser: '^5.48.0'
  terser-webpack-plugin>terser: '^5.48.0'
