name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.19.1

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run ci

      - name: npm auth setup
        run: |
          pnpm logout
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          pnpm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to NPM
        run: pnpm run release:publish

      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          files: packages/*/*.vsix
          fail_on_unmatched_files: true
